### ISSUE TITLE
Base Stats + Gear

### ISSUE THREAD

**Issue by bjggi** [IzaKastra/wsdist#3]
For **MalevolenceA + B**, could BRD be added too. Even, Aeneas R15 seems to beat it for AE, when i added it manually?  
For Capes, INT for BRD would be great too.

**Karieyh_Ring** did u remove it on the List on purpose? 

Would it be possible to add **Rostam** for Cor? Looking at the AE Set.

I hope its fine if i report such things here. If u don't like it, please tell me ;)

Here are some Base Stats from Gaol. If u need more or something is off, feel free to respond. Sorry if u already saw it on the closed thread, i wasn't sure.

--- SAM lvl 99 (Master lvl50) Hume

'STR':143,
'DEX':143,
'VIT':143,
'AGI':140,
'INT':137,
'MND':137,
'CHR':140,

--- WHM lvl 99 (no Master) Hume

'STR':90,
'DEX':84,
'VIT':90,
'AGI':87,
'INT':87,
'MND':97,
'CHR':93,

--- RDM lvl 99 (no Master) Hume

'STR':90,
'DEX':90,
'VIT':87,
'AGI':87,
'INT':93,
'MND':93,
'CHR':90,

--- DRG lvl 99 (Master lvl40) Hume

'STR':135,
'DEX':130,
'VIT':133,
'AGI':130,
'INT':124,
'MND':127,
'CHR':133,

--- WAR lvl 99 (no Master) Hume

'STR':97,
'DEX':93,
'VIT':90,
'AGI':93,
'INT':84,
'MND':84,
'CHR':87,

--- COR lvl 99 (no Master) Hume

'STR':87,
'DEX':93,
'VIT':87,
'AGI':95,
'INT':93,
'MND':87,
'CHR':87,

--- BRD lvl 99 (no Master) Hume

'STR':90,
'DEX':90,
'VIT':90,
'AGI':84,
'INT':90,
'MND':90,
'CHR':95,

--- BLU lvl 99 (no Master) Hume

'STR':87,
'DEX':87,
'VIT':87,
'AGI':87,
'INT':87,
'MND':87,
'CHR':87,

--- MNK lvl 99 (Master lvl40) Hume

'STR':133,
'DEX':135,
'VIT':137,
'AGI':124,
'INT':121,
'MND':130,
'CHR':127,

--- THF lvl 99 (no Master) Hume

'STR':90,
'DEX':97,
'VIT':90,
'AGI':95,
'INT':93,
'MND':81,
'CHR':81,

**Comment by IzaKastra** [comment]
> For MalevolenceA + B, could BRD be added too. Even, Aeneas R15 seems to beat it for AE, when i added it manually?
> For Capes, INT for BRD would be great too.

I'll fix the jobs on Malevolence and add BRD INT capes later today. Thanks for the note.

> Karieyh_Ring did u remove it on the List on purpose?

I did remove Karieyh ring on purpose. I was tired of seeing in show up when I tested sets. I'll re-add the +1 version later today.

> Would it be possible to add Rostam for Cor? Looking at the AE Set.

I can do this, but the code can't handle "Chance of Double Damage" or "Chance of Follow-up attack" for TP sets yet. Technically I haven't officially added TP set support yet anyway.

> I hope its fine if i report such things here. If u don't like it, please tell me ;)

This is fine. Missing gear and incorrect jobs are technically issues.

> Here are some Base Stats from Gaol. If u need more or something is off, feel free to respond. Sorry if u already saw it on the closed thread, i wasn't sure.

This is perfect. I'll add these as well. I didn't see the update to the closed thread. I assumed it would message me if somebody replied again.
