### ISSUE TITLE
Weapon skill dropdown bugged in latest master commit

### ISSUE THREAD

**Issue by RagingMonkeyMan** [IzaKastra/wsdist#4]
Looks like the weapon skill drop down isn't populating any weapon skills except the NIN katana ones. Tried changing the main and sub job and the list isn't updating.

**Comment by RagingMonkeyMan** [comment]
I just realized that I had to change the main weapon at the bottom of the GUI in order to populate the correct weapon skills. Not sure if this was intended or not. If so, then disregard this issue.

**Comment by IzaKastra** [comment]
This was intended. The code has a lot of weapon skills now. I was getting tired of scrolling through so many so I made it only show the weapon skills that your main/ranged weapons can use.
