### ISSUE TITLE
gear.py: Kasuga Kote +3 missing WSD+12%

### ISSUE THREAD

**Issue by IzaKastra** [IzaKastra/wsdist#5]
Replace current line with:

Kasuga_Kote = {"Name":"Kasuga Kote +3","STR":24, "DEX":47, "VIT":47, "AGI":23, "INT":21, "MND":39, "CHR":31, "Accuracy":62, "Attack":62, "Ranged Accuracy":62, "Ranged Attack":62, "Magic Accuracy":62, "Gear Haste":4, "Weaponskill Damage":12, "Jobs":["sam"]}

**Comment by IzaKastra** [comment]
Kasuga_Kote = {"Name":"Kasuga Kote +3","STR":24, "DEX":47, "VIT":47, "AGI":23, "INT":21, "MND":39, "CHR":31, "Accuracy":62, "Attack":62, "Ranged Accuracy":62, "Ranged Attack":62, "Magic Accuracy":62, "Gear Haste":4, "Weaponskill Damage":12, "Jobs":["sam"]}

**Comment by IzaKastra** [comment]
Samurai AF+3 missing Store TP:

Wakido_Domaru = {"Name":"Wakido Domaru +3","STR":41, "DEX":31, "VIT":41, "AGI":31, "INT":31, "MND":31, "CHR":31, "Accuracy":57, "Gear Haste":3, "Store TP":9, "Jobs":["sam"]}

Wakido_Kote = {"Name":"Wakido Kote +3","STR":24, "DEX":40, "VIT":40, "AGI":17, "INT":20, "MND":36, "CHR":30, "Accuracy":48, "Gear Haste":4, "Store TP":7, "Jobs":["sam"]}

**Comment by IzaKastra** [comment]
Monk Empyrean body+3 gives WSD+12% only when Impetus is up. Currently it always applies WSD+12%

**Comment by bjggi** [comment]
Sorry for hijacking, just some things i noticed:

**Regal Earring** missing BLU
**Hashishin_Kavuk** missing Magic Att Bonus +51

**Comment by IzaKastra** [comment]
Thanks. I'll fix these when I fix the others in a few days.

**Comment by bjggi** [comment]
Another thing i noticed when selecting Ody Rank25: Schere_Earring25 is missing in ears and ears2. Would u add Coiste Bodhar25 too?

About the Tachi Fudo thing i wrote in ffxiah, i checked the files but no blank found.

Edit: Would it be possible to add Fell Cleave?

**Comment by bjggi** [comment]
Oh would it also be possible to add Requiescat, would love to get rid of so much Gear i just have for this WS Set... Thx as always and have a good New Year!

**Comment by IzaKastra** [comment]
I've corrected the gear-related issues mentioned in this issue thread.

I've also added Requiescat and Fell Cleave. Let me know if you see any issues with them.

I'll add lower-ranked Odyssey accessories and weapons later.

I'm seeing Doji beat Masa for high-buff Tachi Fudo at 1000-1300 TP, but I can't recreate Doji winning at 2000 TP.
