### ISSUE TITLE
Lustra Subligar D Path wrong stats

### ISSUE THREAD

**Issue by buddyslack** [IzaKastra/wsdist#7]
Lustratio_SubligarD = {"Name":"Lustratio Subligar +1","Name2":"Lustratio Subligar +1 R15D","STR":0+15, "DEX":35+15,"Attack":38, "Jobs":["war","thf","pld","drk","bst","brd","drg","dnc","run",]}

Correct stats would be STR:0  DEX:35+0 Attack 38+30

**Comment by IzaKastra** [comment]
The most recent version of the code has removed that item entirely since Path D seems pretty useless with the correct stats.
